--------------------------------------------------------
--  File created - понедельник-окт€бр€-01-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ORDERITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVT612_ANOSOV"."ORDERITEMS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MOVINGINFORMATIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVT612_ANOSOV"."MOVINGINFORMATIONS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CATEGORIES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVT612_ANOSOV"."CATEGORIES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence POSITIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVT612_ANOSOV"."POSITIONS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RECIPEITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVT612_ANOSOV"."RECIPEITEMS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENUS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVT612_ANOSOV"."MENUS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STREETS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVT612_ANOSOV"."STREETS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COOPERATORS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVT612_ANOSOV"."COOPERATORS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVT612_ANOSOV"."PRODUCTS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVT612_ANOSOV"."ORDERS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DISHES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVT612_ANOSOV"."DISHES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RECIPES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AVT612_ANOSOV"."RECIPES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "AVT612_ANOSOV"."ORDERS" 
   (	"ID" NUMBER, 
	"DATETIME" TIMESTAMP (6), 
	"COOPERATORID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSITIONS
--------------------------------------------------------

  CREATE TABLE "AVT612_ANOSOV"."POSITIONS" 
   (	"ID" NUMBER, 
	"POSITION" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "AVT612_ANOSOV"."PRODUCTS" 
   (	"ID" NUMBER, 
	"NAME" NCHAR(15), 
	"PRICE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOVINGINFORMATIONS
--------------------------------------------------------

  CREATE TABLE "AVT612_ANOSOV"."MOVINGINFORMATIONS" 
   (	"ID" NUMBER, 
	"COOPERATORID" NUMBER, 
	"POSITIONID" NUMBER, 
	"REASONFORTRANSLATION" VARCHAR2(50 BYTE), 
	"ORDERNUMBER" NUMBER, 
	"ORDERDATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DISHES
--------------------------------------------------------

  CREATE TABLE "AVT612_ANOSOV"."DISHES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(15 BYTE), 
	"COOPERATORID" NUMBER, 
	"RECIPEID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENUS
--------------------------------------------------------

  CREATE TABLE "AVT612_ANOSOV"."MENUS" 
   (	"ID" NUMBER, 
	"DISHID" NUMBER, 
	"COOPERATORID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECIPEITEMS
--------------------------------------------------------

  CREATE TABLE "AVT612_ANOSOV"."RECIPEITEMS" 
   (	"ID" NUMBER, 
	"RECIPEID" NUMBER, 
	"PRODUCTID" NUMBER, 
	"COUNTDISH" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERITEMS
--------------------------------------------------------

  CREATE TABLE "AVT612_ANOSOV"."ORDERITEMS" 
   (	"ID" NUMBER, 
	"DISHID" NUMBER, 
	"ORDERID" NUMBER, 
	"NOTE" VARCHAR2(25 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STREETS
--------------------------------------------------------

  CREATE TABLE "AVT612_ANOSOV"."STREETS" 
   (	"ID" NUMBER, 
	"STREET" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "AVT612_ANOSOV"."CATEGORIES" 
   (	"ID" NUMBER, 
	"POSITIONID" NUMBER, 
	"CATEGORY" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COOPERATORS
--------------------------------------------------------

  CREATE TABLE "AVT612_ANOSOV"."COOPERATORS" 
   (	"ID" NUMBER, 
	"FIRSTNAME" VARCHAR2(15 BYTE), 
	"SECONDNAME" VARCHAR2(15 BYTE), 
	"MIDDLENAME" VARCHAR2(15 BYTE), 
	"CITY" VARCHAR2(15 BYTE), 
	"STREETID" NUMBER, 
	"BUILDINGNUMBER" NUMBER, 
	"FLATNUMBER" NUMBER, 
	"BIRTHHDAY" DATE, 
	"SALARY" NUMBER, 
	"STATUS" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECIPES
--------------------------------------------------------

  CREATE TABLE "AVT612_ANOSOV"."RECIPES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into AVT612_ANOSOV.ORDERS
SET DEFINE OFF;
Insert into AVT612_ANOSOV.ORDERS (ID,DATETIME,COOPERATORID) values ('1',to_timestamp('01.10.18 17:46:39,441000000','DD.MM.RR HH24:MI:SSXFF'),'1');
REM INSERTING into AVT612_ANOSOV.POSITIONS
SET DEFINE OFF;
Insert into AVT612_ANOSOV.POSITIONS (ID,POSITION) values ('3','cocker');
Insert into AVT612_ANOSOV.POSITIONS (ID,POSITION) values ('4','waiter');
Insert into AVT612_ANOSOV.POSITIONS (ID,POSITION) values ('5','seller');
Insert into AVT612_ANOSOV.POSITIONS (ID,POSITION) values ('6','boss');
Insert into AVT612_ANOSOV.POSITIONS (ID,POSITION) values ('21','programmer');
Insert into AVT612_ANOSOV.POSITIONS (ID,POSITION) values ('22','programmer');
Insert into AVT612_ANOSOV.POSITIONS (ID,POSITION) values ('23','programmer');
Insert into AVT612_ANOSOV.POSITIONS (ID,POSITION) values ('24','programmer');
Insert into AVT612_ANOSOV.POSITIONS (ID,POSITION) values ('25','backender');
Insert into AVT612_ANOSOV.POSITIONS (ID,POSITION) values ('26','frontender');
REM INSERTING into AVT612_ANOSOV.PRODUCTS
SET DEFINE OFF;
Insert into AVT612_ANOSOV.PRODUCTS (ID,NAME,PRICE) values ('1','kartoshka      ','42');
Insert into AVT612_ANOSOV.PRODUCTS (ID,NAME,PRICE) values ('2','morkovy        ','15');
Insert into AVT612_ANOSOV.PRODUCTS (ID,NAME,PRICE) values ('3','luk            ','10');
Insert into AVT612_ANOSOV.PRODUCTS (ID,NAME,PRICE) values ('4','svekla         ','15');
Insert into AVT612_ANOSOV.PRODUCTS (ID,NAME,PRICE) values ('5','chesnok        ','25');
REM INSERTING into AVT612_ANOSOV.MOVINGINFORMATIONS
SET DEFINE OFF;
REM INSERTING into AVT612_ANOSOV.DISHES
SET DEFINE OFF;
Insert into AVT612_ANOSOV.DISHES (ID,NAME,COOPERATORID,RECIPEID) values ('1','cesar','1','1');
REM INSERTING into AVT612_ANOSOV.MENUS
SET DEFINE OFF;
REM INSERTING into AVT612_ANOSOV.RECIPEITEMS
SET DEFINE OFF;
Insert into AVT612_ANOSOV.RECIPEITEMS (ID,RECIPEID,PRODUCTID,COUNTDISH) values ('2','1','1','1');
Insert into AVT612_ANOSOV.RECIPEITEMS (ID,RECIPEID,PRODUCTID,COUNTDISH) values ('3','1','2','1');
Insert into AVT612_ANOSOV.RECIPEITEMS (ID,RECIPEID,PRODUCTID,COUNTDISH) values ('4','1','3','3');
REM INSERTING into AVT612_ANOSOV.ORDERITEMS
SET DEFINE OFF;
Insert into AVT612_ANOSOV.ORDERITEMS (ID,DISHID,ORDERID,NOTE) values ('1','1','1','без соли');
REM INSERTING into AVT612_ANOSOV.STREETS
SET DEFINE OFF;
Insert into AVT612_ANOSOV.STREETS (ID,STREET) values ('1','baganskaya');
Insert into AVT612_ANOSOV.STREETS (ID,STREET) values ('2','baykalskaya');
Insert into AVT612_ANOSOV.STREETS (ID,STREET) values ('3','marksa');
Insert into AVT612_ANOSOV.STREETS (ID,STREET) values ('4','romantikov');
Insert into AVT612_ANOSOV.STREETS (ID,STREET) values ('5','baumana');
Insert into AVT612_ANOSOV.STREETS (ID,STREET) values ('6','belousova');
Insert into AVT612_ANOSOV.STREETS (ID,STREET) values ('7','beluhi');
Insert into AVT612_ANOSOV.STREETS (ID,STREET) values ('8','biyskaya');
Insert into AVT612_ANOSOV.STREETS (ID,STREET) values ('9','bronnaya');
Insert into AVT612_ANOSOV.STREETS (ID,STREET) values ('10','vesenyaya');
REM INSERTING into AVT612_ANOSOV.CATEGORIES
SET DEFINE OFF;
Insert into AVT612_ANOSOV.CATEGORIES (ID,POSITIONID,CATEGORY) values ('3','2','shief');
REM INSERTING into AVT612_ANOSOV.COOPERATORS
SET DEFINE OFF;
Insert into AVT612_ANOSOV.COOPERATORS (ID,FIRSTNAME,SECONDNAME,MIDDLENAME,CITY,STREETID,BUILDINGNUMBER,FLATNUMBER,BIRTHHDAY,SALARY,STATUS) values ('1','anosov','konstantin','gennadievich','novosibirsk','4','9','47',to_date('17.07.98','DD.MM.RR'),'99999999','work');
REM INSERTING into AVT612_ANOSOV.RECIPES
SET DEFINE OFF;
Insert into AVT612_ANOSOV.RECIPES (ID,NAME) values ('1','Salad');
Insert into AVT612_ANOSOV.RECIPES (ID,NAME) values ('2','Sup');
Insert into AVT612_ANOSOV.RECIPES (ID,NAME) values ('3','Salad');
Insert into AVT612_ANOSOV.RECIPES (ID,NAME) values ('4','salad');
Insert into AVT612_ANOSOV.RECIPES (ID,NAME) values ('5','sup');
Insert into AVT612_ANOSOV.RECIPES (ID,NAME) values ('6','burger');
--------------------------------------------------------
--  DDL for Index ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVT612_ANOSOV"."ORDERS_PK" ON "AVT612_ANOSOV"."ORDERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POSITIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVT612_ANOSOV"."POSITIONS_PK" ON "AVT612_ANOSOV"."POSITIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVT612_ANOSOV"."PRODUCTS_PK" ON "AVT612_ANOSOV"."PRODUCTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MOVINGINFORMATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVT612_ANOSOV"."MOVINGINFORMATIONS_PK" ON "AVT612_ANOSOV"."MOVINGINFORMATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DISHES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVT612_ANOSOV"."DISHES_PK" ON "AVT612_ANOSOV"."DISHES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVT612_ANOSOV"."MENUS_PK" ON "AVT612_ANOSOV"."MENUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RECIPEITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVT612_ANOSOV"."RECIPEITEMS_PK" ON "AVT612_ANOSOV"."RECIPEITEMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDERITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVT612_ANOSOV"."ORDERITEMS_PK" ON "AVT612_ANOSOV"."ORDERITEMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STREETS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVT612_ANOSOV"."STREETS_PK" ON "AVT612_ANOSOV"."STREETS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CATEGORIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVT612_ANOSOV"."CATEGORIES_PK" ON "AVT612_ANOSOV"."CATEGORIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COOPERATORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVT612_ANOSOV"."COOPERATORS_PK" ON "AVT612_ANOSOV"."COOPERATORS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RECIPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AVT612_ANOSOV"."RECIPES_PK" ON "AVT612_ANOSOV"."RECIPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger MENUS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."MENUS_TRG1" 
BEFORE INSERT ON MENUS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MENUS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."MENUS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCTS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."PRODUCTS_TRG1" 
BEFORE INSERT ON PRODUCTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PRODUCTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."PRODUCTS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECIPEITEMS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."RECIPEITEMS_TRG" 
BEFORE INSERT ON RECIPEITEMS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."RECIPEITEMS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDERITEMS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."ORDERITEMS_TRG1" 
BEFORE INSERT ON ORDERITEMS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ORDERITEMS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."ORDERITEMS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DISHES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."DISHES_TRG" 
BEFORE INSERT ON DISHES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."DISHES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECIPES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."RECIPES_TRG" 
BEFORE INSERT ON RECIPES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."RECIPES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COOPERATORS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."COOPERATORS_TRG1" 
BEFORE INSERT ON COOPERATORS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT COOPERATORS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."COOPERATORS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MENUS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."MENUS_TRG" 
BEFORE INSERT ON MENUS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."MENUS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STREETS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."STREETS_TRG1" 
BEFORE INSERT ON STREETS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT STREETS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."STREETS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POSITIONS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."POSITIONS_TRG1" 
BEFORE INSERT ON POSITIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT POSITIONS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."POSITIONS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STREETS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."STREETS_TRG" 
BEFORE INSERT ON STREETS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."STREETS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COOPERATORS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."COOPERATORS_TRG" 
BEFORE INSERT ON COOPERATORS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."COOPERATORS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."ORDERS_TRG" 
BEFORE INSERT ON ORDERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."ORDERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDERS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."ORDERS_TRG1" 
BEFORE INSERT ON ORDERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ORDERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."ORDERS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECIPEITEMS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."RECIPEITEMS_TRG1" 
BEFORE INSERT ON RECIPEITEMS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT RECIPEITEMS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."RECIPEITEMS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATEGORIES_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."CATEGORIES_TRG1" 
BEFORE INSERT ON CATEGORIES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CATEGORIES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."CATEGORIES_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."PRODUCTS_TRG" 
BEFORE INSERT ON PRODUCTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."PRODUCTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DISHES_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."DISHES_TRG1" 
BEFORE INSERT ON DISHES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DISHES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."DISHES_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MOVINGINFORMATIONS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."MOVINGINFORMATIONS_TRG1" 
BEFORE INSERT ON MOVINGINFORMATIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MOVINGINFORMATIONS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."MOVINGINFORMATIONS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECIPES_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."RECIPES_TRG1" 
BEFORE INSERT ON RECIPES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT RECIPES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."RECIPES_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATEGORIES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."CATEGORIES_TRG" 
BEFORE INSERT ON CATEGORIES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."CATEGORIES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MOVINGINFORMATIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."MOVINGINFORMATIONS_TRG" 
BEFORE INSERT ON MOVINGINFORMATIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."MOVINGINFORMATIONS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POSITIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."POSITIONS_TRG" 
BEFORE INSERT ON POSITIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."POSITIONS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDERITEMS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AVT612_ANOSOV"."ORDERITEMS_TRG" 
BEFORE INSERT ON ORDERITEMS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AVT612_ANOSOV"."ORDERITEMS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "AVT612_ANOSOV"."ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "AVT612_ANOSOV"."ORDERS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."ORDERS" MODIFY ("DATETIME" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."ORDERS" MODIFY ("COOPERATORID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSITIONS
--------------------------------------------------------

  ALTER TABLE "AVT612_ANOSOV"."POSITIONS" ADD CONSTRAINT "POSITIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "AVT612_ANOSOV"."POSITIONS" MODIFY ("POSITION" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."POSITIONS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "AVT612_ANOSOV"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "AVT612_ANOSOV"."PRODUCTS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."PRODUCTS" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."PRODUCTS" MODIFY ("PRICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOVINGINFORMATIONS
--------------------------------------------------------

  ALTER TABLE "AVT612_ANOSOV"."MOVINGINFORMATIONS" ADD CONSTRAINT "MOVINGINFORMATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "AVT612_ANOSOV"."MOVINGINFORMATIONS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."MOVINGINFORMATIONS" MODIFY ("COOPERATORID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."MOVINGINFORMATIONS" MODIFY ("POSITIONID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."MOVINGINFORMATIONS" MODIFY ("REASONFORTRANSLATION" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."MOVINGINFORMATIONS" MODIFY ("ORDERNUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."MOVINGINFORMATIONS" MODIFY ("ORDERDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DISHES
--------------------------------------------------------

  ALTER TABLE "AVT612_ANOSOV"."DISHES" ADD CONSTRAINT "DISHES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "AVT612_ANOSOV"."DISHES" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."DISHES" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."DISHES" MODIFY ("COOPERATORID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."DISHES" MODIFY ("RECIPEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENUS
--------------------------------------------------------

  ALTER TABLE "AVT612_ANOSOV"."MENUS" ADD CONSTRAINT "MENUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "AVT612_ANOSOV"."MENUS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."MENUS" MODIFY ("DISHID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."MENUS" MODIFY ("COOPERATORID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECIPEITEMS
--------------------------------------------------------

  ALTER TABLE "AVT612_ANOSOV"."RECIPEITEMS" ADD CONSTRAINT "RECIPEITEMS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "AVT612_ANOSOV"."RECIPEITEMS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."RECIPEITEMS" MODIFY ("RECIPEID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."RECIPEITEMS" MODIFY ("PRODUCTID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."RECIPEITEMS" MODIFY ("COUNTDISH" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERITEMS
--------------------------------------------------------

  ALTER TABLE "AVT612_ANOSOV"."ORDERITEMS" ADD CONSTRAINT "ORDERITEMS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "AVT612_ANOSOV"."ORDERITEMS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."ORDERITEMS" MODIFY ("DISHID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."ORDERITEMS" MODIFY ("ORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STREETS
--------------------------------------------------------

  ALTER TABLE "AVT612_ANOSOV"."STREETS" ADD CONSTRAINT "STREETS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "AVT612_ANOSOV"."STREETS" MODIFY ("STREET" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."STREETS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "AVT612_ANOSOV"."CATEGORIES" ADD CONSTRAINT "CATEGORIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "AVT612_ANOSOV"."CATEGORIES" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."CATEGORIES" MODIFY ("POSITIONID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."CATEGORIES" MODIFY ("CATEGORY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COOPERATORS
--------------------------------------------------------

  ALTER TABLE "AVT612_ANOSOV"."COOPERATORS" ADD CONSTRAINT "COOPERATORS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "AVT612_ANOSOV"."COOPERATORS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."COOPERATORS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."COOPERATORS" MODIFY ("SECONDNAME" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."COOPERATORS" MODIFY ("CITY" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."COOPERATORS" MODIFY ("STREETID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."COOPERATORS" MODIFY ("BUILDINGNUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."COOPERATORS" MODIFY ("BIRTHHDAY" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."COOPERATORS" MODIFY ("SALARY" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."COOPERATORS" MODIFY ("STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECIPES
--------------------------------------------------------

  ALTER TABLE "AVT612_ANOSOV"."RECIPES" ADD CONSTRAINT "RECIPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "AVT612_ANOSOV"."RECIPES" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "AVT612_ANOSOV"."RECIPES" MODIFY ("NAME" NOT NULL ENABLE);
